sudo: required
language: java
jdk:
  - oraclejdk8
addons:
  firefox: "38.8.0esr"
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - ARCHETYPE_VERSION=5.2.2-SNAPSHOT
    - VERSION=1.0.0-SNAPSHOT
    - CARGO_DAEMON_WEBAPP_VERSION=1.4.17
  matrix:
    # todo
    - TARGET_TUTORIAL=todo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-archetype
    - TARGET_TUTORIAL=todo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-mybatis3-archetype
    - TARGET_TUTORIAL=todo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
    - TARGET_TUTORIAL=todo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-jpa-archetype
    - TARGET_TUTORIAL=todo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-jpa-archetype
    # todo-rest
    - TARGET_TUTORIAL=todo-rest ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-archetype
    - TARGET_TUTORIAL=todo-rest ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-mybatis3-archetype
    - TARGET_TUTORIAL=todo-rest ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
    - TARGET_TUTORIAL=todo-rest ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-jpa-archetype
    - TARGET_TUTORIAL=todo-rest ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-jpa-archetype
    # first-spring-security
    - TARGET_TUTORIAL=first-spring-security ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-web-blank-mybatis3-archetype
    - TARGET_TUTORIAL=first-spring-security ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
    # session-tutorial-init
    - TARGET_TUTORIAL=session-tutorial-init ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
    # session-tutorial-complete
    - TARGET_TUTORIAL=session-tutorial-complete ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
    # secure-login-demo
    - TARGET_TUTORIAL=secure-login-demo ARCHETYPE_ARTIFACT_ID=terasoluna-gfw-multi-web-blank-mybatis3-archetype
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bash ./common/scripts/change-maven-settings.sh
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./
  - java -jar ./cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script: 
  - echo "==================== Validate code format ===================="
  - |
    mvn xml:check-format
    mvn formatter:validate
    
  - echo "==================== Generate Tutorial App ===================="
  - |
    bash ./${TARGET_TUTORIAL}/scripts/create-app.sh
    
  - echo "==================== Build Tutorial App and execute Tests ===================="
  - |
    POM=./${TARGET_TUTORIAL}/target-project/${ARTIFACT_ID}/pom.xml
    if test `echo $ARCHETYPE_ARTIFACT_ID | grep multi`;then
      echo "execute ./mvn-multiproject-build"
      bash ./common/scripts/mvn-multiproject-build.sh "$POM"
    else
      echo "execute ./mvn-singleproject-build"
      bash ./common/scripts/mvn-singleproject-build.sh "$POM"
    fi
    exit $?
